### ISSUE TITLE
Spanish caption broken in Able Player tests

### ISSUE THREAD

**Issue by kensgists** [ableplayer/ableplayer#120] opened 2015-04-13 15:18 UTC
Spanish caption on Able Player test site not showing captions. Audio description does show in transcript region, but without captions appearing. Visible in tests 7 and German version of 7.

**Comment by Egyrs** [comment] 2015-04-13 16:52
You are right! And the spanish transcription is not update (there still the automatic translation that is not my translation).

**Comment by Egyrs** [comment] 2015-04-13 16:53
Is the same for example 16. It seem to me that the problem is only that the examples page is not taken the last version.

**Comment by terrill** [comment] 2015-04-13 18:00
Looks like the various branches have gotten out of sync. Working on that now..

**Comment by terrill** [comment] 2015-04-13 18:20
There was actually another problem @Egyrs - you translated the word NOTE to NOTA.  This is actually a keyword in the WebVTT file, indicating the start of a comment block. I translated it back to NOTE and it's working now. Fixed in 0b78b4415d185b333d1a10053b858eb6a7f9bd87 on the develop branch. I'll merge that into Master and gh-pages later today after fixing a few other issues

**Closed by terrill** 2015-04-13 18:20 UTC

**Comment by Egyrs** [comment] 2015-04-13 20:14
OK, sorry, I take "note" :-)
