### ISSUE TITLE
Controls invisible when changing colours with Firefox

### ISSUE THREAD

**Issue by selfthinker** [ableplayer/ableplayer#400] opened 2020-01-21 16:48 UTC
When changing colours with Firefox to a dark colour scheme nearly all of the controls become completely invisible, only the seeker stays visible.

This is a screenshot of how the player from the [simple YouTube example](https://ableplayer.github.io/ableplayer/demos/youtube.html) looks:
<img width="543" alt="" src="https://user-images.githubusercontent.com/108893/72823752-171afa80-3c6c-11ea-8850-adf07a8bb250.png">

You can change colours in Firefox via Preferences > Colors... > change Text and Background colours accordingly and choose "Always" for "Override the colors specified by the page with your selections above".

The controls are visible when choosing a light colour scheme, like black on yellow. But not when choosing a dark colour scheme, specifically with a black background colour, but other dark background colours will also be difficult to see.

You can still somewhat operate the player when you tab through the controls as you will be able to see the tooltips. But not everyone who relies on adjusted colours would know that.

Changing colours via Windows High Contrast mode works mostly fine. (I see there has been some work on it via #26.) Both have in common that the volume slider is invisible as well when activated.

**Comment by terrill** [comment] 2020-02-26 23:21
I created a [Contrast Test](http://terrillthompson.com/tests/contrast.html) page to test how various high contrast themes and tools render text, buttons, and SVG content.  It's common for high contrast themes to handle buttons differently than regular text. 

In Windows 10, there are four high contrast themes provided by default with the OS, and these are all respected within Edge. Three of the themes change the background to black (everywhere, including buttons), and change the foreground text and borders to yellow, green, or white, depending on the theme. All buttons for all themes are changed to black on white, regardless of whether the button content is text or SVG. They're still still visible, and they're high contrast. 

In Chrome, there are various extensions that provide high contrast functionality. The one I have installed is [High Contrast](https://chrome.google.com/webstore/detail/high-contrast/djcfdncoelnlbldjfhinnjlhdjlikmph) by Google. All of its themes handle text, buttons, borders, and SVGs identically within the theme. 

The problem is Firefox. When you change the text and background colors, it changes background colors everywhere to whatever color the user selected (including the background colors on buttons). However, it always changes the foreground color on buttons to black, rather than the user's chosen text color. This is true whether the button content is text or SVG. So in your example @selfthinker, you chose black as a background color, so the background color of Able Player's buttons changed to black, but the foreground color of Able Player's buttons also changed to black.        

Since this problem is unique to buttons, it could be fixed within Able Player by changing all `<button>` elements to `<div role="button">`, but I'm hesitant to do that as it's a major change that could potentially have consequences. It would require extensive testing. Instead I'm inclined to file a bug with Mozilla and see what sort of response I get.   

The volume slider is a separate issue. I've reopened #26 and added a note to look into that.

**Comment by terrill** [comment] 2020-02-27 23:39
This has been fixed in 51fdbd8496b37e5ca44e59ebc7caa9a2eb712de5

I went ahead and changed all `<button>` elements to `<div role="button">` on the controller. That seems like the best solution as it users the user's preferred foreground color for the icons on the buttons.

**Closed by terrill** 2020-02-27 23:39 UTC
Labels: bug

**Comment by selfthinker** [comment] 2020-03-16 13:10
I should have mentioned that this is a known bug in Firefox which I have reported (over 3 years ago) at https://bugzilla.mozilla.org/show_bug.cgi?id=1335476

Thanks for the quick change.

There are two things to be aware of when changing `<button>` to `<div role="button">`:

1. Keyboard only users (which includes most screen reader users) will expect buttons to work with the space key in addition to the enter key. It's not a full barrier but an annoyance if the space key doesn't work.
2. Speech recognition / voice control users might not be able to refer to the buttons as "button" anymore (say e.g. "click play button"). I would recommend testing with Dragon etc to make sure it still works as expected.

I have not tested these in the new implementation yet. It would be good to test them properly with these pitfalls in mind.

**Comment by terrill** [comment] 2020-03-25 17:11
@selfthinker regarding the two possible issues you identified: 
1. Able Player "buttons" (even though no longer technically HTML buttons) can still be toggled with a spacebar. That's being handled in Able Player's JavaScript code. 
2. I just tested with Dragon, and it does recognize all "buttons" as clickable. "Click play button" doesn't work, but "Click play" does, which is easier to say anyway. According to Nuance's Dragon help page on [Web browser basics](https://www.nuance.com/products/help/dragon/dragon-for-pc/enx/professionalgroup/main/Content/Web/web_basics.htm), users don't have to say "button" to click a button. They can simply say "Click" followed by all or part of the button name.
