### ISSUE TITLE
Talkback with Audio Player Repeats "Playing, Playing, Playing"

### ISSUE THREAD

**Issue by bmhall3** [ableplayer/ableplayer#276] opened 2017-03-27 16:57 UTC
Talkback repeats "playing, playing, playing" on Andriod.  This does not happen with iOS on mobile.

**Comment by terrill** [comment] 2017-10-09 19:01
Duplicate of #295.  This issue was actually created first (sorry about the duplication) but the other one contains a bit more details so I'm keeping it open.

**Closed by terrill** 2017-10-09 19:01 UTC
Labels: bug
