### ISSUE TITLE
Prev / next playlist buttons?

### ISSUE THREAD

**Issue by lardconcepts** [ableplayer/ableplayer#366] opened 2019-07-12 20:59 UTC
Pretty much a basic essential of a playlist is previous and next, and I was surprised to find this https://github.com/ableplayer/ableplayer/issues/200 when I first looked at AblePlayer a couple of years ago. 
But I'm pleased to see this in the code: "Previous/Next buttons"
https://github.com/ableplayer/ableplayer/blob/master/build/ableplayer.js#L261

However, I can't find any documentation. Any ideas?

**Comment by lardconcepts** [comment] 2019-07-13 20:27
Or alternatively, how would one send a "click" to simulate end of track? I've tried things like 
$('#audio1')[0].ended=true
but no luck

**Comment by lardconcepts** [comment] 2019-07-15 10:29
Been trying to work on this over the weekend, hacking the playlist with a jQuery.click (but that just takes focus from the user).
I also tried setting data-seek-interval="10000" which kind of works, but with a long track and slow internet, everything hangs while the media loads so it can seek to the end.
Really would appreciate any other ideas.

**Comment by terrill** [comment] 2019-07-17 22:48
Thanks @lardconcepts for bringing this issue to the surface again. I'm going to close the current issue though since it's essentially a duplicate of #200.  The discussion in the latter issue ultimately led to a technical solution that seemed feasible, as spelled out in my [comment on May 21, 2017](https://github.com/ableplayer/ableplayer/issues/200#issuecomment-302939877). As noted in that comment, the remaining hurdle was actual support for accessible playlists, which wasn't implemented until [version 4.0](https://github.com/ableplayer/ableplayer/releases/tag/v4.0), just released in April.   

I have an extremely busy couple of weeks ahead, but I plan to work on this in August. Stay tuned...

**Closed by terrill** 2019-07-17 22:48 UTC
