### ISSUE TITLE
Enable/Disable button

### ISSUE THREAD

**Issue by haidar1000** [ableplayer/ableplayer#353] opened 2018-12-19 08:16 UTC
I want to hide preferences button and Slower/Faster buttons.
Thank you so much for AblePlayer, it is very useful.

**Comment by terrill** [comment] 2018-12-19 23:13
@haidar1000 that isn't currently possible, nor advisable since both buttons play important roles in accessibility.  That said, there have been lots of requests for a player that's more customizable by designers, developers, and content authors. I'm not willing to compromise user accessibility to attain that, but I'm open to ideas for how to attain a balance between the two needs.        

I'm closing this issue, but #305 (related) is still open. If you'd like to lend your voice to the discussion over there, please do. Thanks!

**Closed by terrill** 2018-12-19 23:13 UTC
